### ISSUE TITLE
Imagens disponíveis localmente

### ISSUE THREAD

**Issue by MatheusSchwarz** [allanbmartins/Projeto_ETL_RFB_IBGE_ANP#1]
Obrigado por compartilhar o material, Allan! Sou novo na programação e acredito que o teu projeto irá me ajudar a resolver um problema que enfrento há tempos. Uma coisa que eu percebi no teu código que estava me dando erro: as 3 imagens que são carregadas para executar o tkinker estão salvas localmente, corrigi isso só colocando uma imagem qualquer para fazer o programa rodar.

**Comment by allanbmartins** [comment]
Bom dia, Matheus, primeiramente, eu que agradeço o feedback, em segundo não tem o que agradecer, o meu intuito na disponibilização do projeto foi auxiliar o máximo de pessoas possíveis que estavam com este mesmo problema na obtenção dos dados abertos públicos, quanto ao erro que você teve não consegui reproduzir aqui, mesmo testando em outras duas máquinas do zero, baixando do github, mesmo assim alterei o método de localização das 6 imagens utilizadas no menu GUI Tkinter, para ver se não se repete o problema, caso necessite de ajuda estou a disposição, e por fim, não esqueça de dar uma estrela para aumentar a relevância do projeto no github, e caso possível também compartilhar o link do projeto nas suas redes sociais (linkedin e outros) para que mais pessoas possam ser auxiliadas.
