### ISSUE TITLE
Dados RAIS

### ISSUE THREAD

**Issue by biographicscontact** [allanbmartins/Projeto_ETL_RFB_IBGE_ANP#2]
Parabéns pelo projeto Allan! Fantástico!

Uma questão: fiquei na dúvida de ontem saem os dados da RAIS - que são lidos pelo script [F_Script_RAIS.py](https://github.com/allanbmartins/Projeto_ETL_RFB_IBGE_ANP/blob/master/src/F_Script_RAIS.py)

obrigado!

**Comment by allanbmartins** [comment]
Boa Tarde, obrigado, os Scripts dos dados da RAIS não é um dado aberto, a obtenção só mediante solicitação formal link: "Solicitar bases de dados identificados da Rais e do Caged para fins estatísticos" (https://www.gov.br/pt-br/servicos/solicitar-acesso-aos-dados-identificados-rais-e-caged), já os dados de SGI e FT, são bases internas, com dados também não abertos, por isso não coloquei no menu GUI, estes scripts são para uso interno no meu trabalho só estão para versionamento de código.

**Comment by biographicscontact** [comment]
Tá legal obrigado!

**Comment by fabioselau077** [comment]
Aproveitando a issue, se o dataset é atualizado 1x por mês, como sites que utilizam esse dataset possuem os novos CNP's criados todos os dias? Casadosdados, por exemplo, você consegue recuperar empresas geradas ontem e hoje, por exemplos.

**Comment by allanbmartins** [comment]
Boa tarde, Fabio

Acredito que o site casa dos dados obtém através da api da receita "https://www.gov.br/conecta/catalogo/apis/consulta-cnpj" que você consegue só pegar as informações que foram atualizadas da base da receita sem ter que pegar todo o resto, mas acredito que deve ter algum custo, agora não sei como que é bancado se eles vendem algum serviço anexo não sei.

**Comment by fabioselau077** [comment]
> Boa tarde, Fabio
> 
> Acredito que o site casa dos dados obtém através da api da receita "https://www.gov.br/conecta/catalogo/apis/consulta-cnpj" que você consegue só pegar as informações que foram atualizadas da base da receita sem ter que pegar todo o resto, mas acredito que deve ter algum custo, agora não sei como que é bancado se eles vendem algum serviço anexo não sei.

É cara, pelo q vi só o Serpro, mas é pago e pra eles n iriam compensar pagar... Tô achando que eles possuem acesso com alguma esquema, funcionário público de alto cargo, órgão que faz parte do SISP... Algum esquema tem kkkk

Mesmo q for pelo Serpro, lá vc n recupera lista de cnp's, vc n consegue filtrar por exemplo: "Quero todos os cnp's criados ontem", vc literalmente consegue só recuperar dados de um CNPJ, cnpj q vc tem q saber...
