### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by DigoDiniz** [allanbmartins/Projeto_ETL_RFB_IBGE_ANP#3]
Bom Dia Allan.

Sou um simples usuário dos dados e vê nos comentários no Site do gov. RFB vc falando sobre o software que montou como projeto para fazer o Download e tratamento dos dados. Vc pode ajudar um leigo para executar o projeto e fazer os testes?

ABS
Rodrigo

**Comment by allanbmartins** [comment]
Boa Tarde, DigoDiniz, posso lhe ajudar sim, más para executar o projeto, é só seguir a partir do item "Infraestrutura necessária/opcional:", tem um detalhamento e automatizei o máximo possível dentro da ferramenta, más mesmo assim, se tiver dúvidas eu ajudo sim.
