### ISSUE TITLE
Atualização caso o CNPJ já existir

### ISSUE THREAD

**Issue by fabioselau077** [allanbmartins/Projeto_ETL_RFB_IBGE_ANP#4]
Caros, obrigado pelo projeto.

Só tenho uma dúvida, quando a Receita faz atualização dos datasets, elas adicionam uma nova pasta ou somente adiciona os cnpjs nos datasets já existentes?

No caso, falo da atualização do banco de dados, se eu importar uma vez e depois na nova release do dataset eu importar novamente, será importado somente os CNPJ's novos?

Todos os projetos que encontrei até agora ele limpa o banco e importa tudo novamente, acha que dá pra fazer um select antes e caso já existir só dá um update no existente?

Se sim, posso te ajudar nessa questão, posso fazer uma PR.

**Comment by allanbmartins** [comment]
Boa tarde, Fabio

Este banco faz a mesma coisa que a maioria faz no github que é baixar os dados novamente, a receita não coloca só arquivos com dados alterados, sempre coloca todos os arquivos todos juntos arquivos com dados novos e antigos, então não há possibilidade de você baixar só o que é novo porque os antigos foram alterados então todos os arquivos praticamente tem que ser repostos por isso que a maioria ou todos os projetos do github que são grátis são nesse formato de você fazer o download completo do banco, a receita tem uma que ela tem arrecadação com isso para uso com empresas então não seria interessante ela fazer do método que só colocasse os arquivos novos.
