### ISSUE TITLE
Dados não estão sendo salvos

### ISSUE THREAD

**Issue by joaotonaco** [allanbmartins/Projeto_ETL_RFB_IBGE_ANP#5]
Estou usando uma database PostgreSQL online chamada [Neon](https://neon.tech). E os dados não estão sendo salvos nela, apenas foram criadas as tabelas e propriedades.

Estou realizando o processo de RFB clicando em "Executar todos os passos acima em sequência..."

**Comment by allanbmartins** [comment]
Boa tarde, Prezado, Bluee

O projeto foi testado para ser feito em modo local, não tenho ideia porque os dados não estão sendo injetados nesse PostgreSQL online.

Cole aqui numa resposta o conteúdo do arquivo "log.log", para poder tentar descobrir o que está acontecendo.
Nesse arquivo são capturadas toda a execução (INFO e ERROR), OK?
Estou no aguardo do envio.

**Comment by allanbmartins** [comment]
A localização dele é na raiz da pasta do projeto.

**Comment by joaotonaco** [comment]
> A localização dele é na raiz da pasta do projeto.

```
ERROR:[08/16/2023 03:17:39 PM]: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(leitura_csv_insercao_bd_sql) finalizada com erro abaixo: 
 (must be superuser or have privileges of the pg_read_server_files role to COPY from a file
HINT:  Anyone can COPY to stdout or from stdin. psql's \copy command also works for anyone.
)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "C:\Users\Jao\Documents\Projeto_ETL_RFB_IBGE_ANP-master\src\B_Def_Global.py", line 1009, in leitura_csv_insercao_bd_sql
    cur.execute(sql_3)
psycopg2.errors.InsufficientPrivilege: must be superuser or have privileges of the pg_read_server_files role to COPY from a file
HINT:  Anyone can COPY to stdout or from stdin. psql's \copy command also works for anyone.
```

**Comment by allanbmartins** [comment]
A resposta esta justamente aí, é um problema de privilégio de acesso ao seu banco de dados online, veja e link abaixo sobre este problema, não sei se vc vai conseguir resolver, más você pode tentar o que diz no link, por que como disse o escopo do projeto é para uso num banco de dados local, ele não foi pensado para uso online, para isso a melhor maneira seria uso de docker.

Link: https://community.talend.com/s/article/Insufficient-Privilege-must-be-superuser-to-COPY-to-or-from-a-file-error-when-importing-a-file-into-PostgreSQL-DB-YlB0p?language=en_US

**Comment by bluee-js** [comment]
Tentei novamente e agora com a database local, criei um superuser tudo certinho, porém agora o programa diz não ter conseguido ler o arquivo mesmo eu tendo executado o terminal como administrador.

```
ERROR:[08/16/2023 07:13:37 PM]: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(leitura_csv_insercao_bd_sql) finalizada com erro abaixo: 
 (could not open file "C:\xxx\cnpjs\files\dados_rfb\EXTRACTED_FILES_CONVERT\F.K03200$Z.D30708.QUALSCSV._parte_1" for reading: Permission denied
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "C:\xxx\cnpjs\src\B_Def_Global.py", line 1009, in leitura_csv_insercao_bd_sql
    cur.execute(sql_3)
psycopg2.errors.InsufficientPrivilege: could not open file "C:\xxx\cnpjs\files\dados_rfb\EXTRACTED_FILES_CONVERT\F.K03200$Z.D30708.QUALSCSV._parte_1" for reading: Permission denied
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
```
