### ISSUE TITLE
Dados não estão sendo salvos na DB Local

### ISSUE THREAD

**Issue by joaotonaco** [allanbmartins/Projeto_ETL_RFB_IBGE_ANP#6]
Executei tudo como administrador, coloquei o user da db como superuser, mas mesmo assim estou tendo esse erro:

```
ERROR:[08/16/2023 07:13:37 PM]: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(leitura_csv_insercao_bd_sql) finalizada com erro abaixo: 
 (could not open file "C:\xxx\cnpjs\files\dados_rfb\EXTRACTED_FILES_CONVERT\F.K03200$Z.D30708.QUALSCSV._parte_1" for reading: Permission denied
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "C:\xxx\cnpjs\src\B_Def_Global.py", line 1009, in leitura_csv_insercao_bd_sql
    cur.execute(sql_3)
psycopg2.errors.InsufficientPrivilege: could not open file "C:\xxx\cnpjs\files\dados_rfb\EXTRACTED_FILES_CONVERT\F.K03200$Z.D30708.QUALSCSV._parte_1" for reading: Permission denied
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
```

**Comment by allanbmartins** [comment]
Bom dia, Prezado Bluee
É um problema de privilégio do seu usuário, encontrei esses links abaixo, que podem te ajudar:
https://github.com/sqlalchemy/sqlalchemy/discussions/6466
https://stackoverflow.com/questions/60138692/sqlalchemy-psycopg2-errors-insufficientprivilege-permission-denied-for-relation

OBS.: Nesse projeto as conexões são com o usuário postgresql e este usuário tem que ter privilégios completos no postgersql.
https://www.devmedia.com.br/gerenciando-usuarios-e-permissoes-no-postgresql/14301

**Comment by allanbmartins** [comment]
PSQL – Visualizar lista de usuário existentes em PostgreSQL
Utilizando psql, para visualizar a relação de usuários, basta:
# \du

**Comment by allanbmartins** [comment]
[Postgresql: what does GRANT ALL PRIVILEGES ON DATABASE do?](https://serverfault.com/questions/198002/postgresql-what-does-grant-all-privileges-on-database-do)

**Comment by allanbmartins** [comment]
Espero que algum desses links possa te ajudar a resolver a liberação de acesso completo ao PostgreSQL

**Comment by allanbmartins** [comment]
Apesar que alguns posts mencionam que esse erro pode ser de falta de privilégio não no banco, más sim no seu sistema operacional, notei que vc colocou no drive C:, se possível faça o teste no D:, e verifique se seu login/usuário tem acesso completo de administrador no pc, por desencargo de consciência.

**Comment by allanbmartins** [comment]
E uma pergunta, você está utilizando o VSCODE  e executando o pelo GUI Tkinter?

**Comment by joaotonaco** [comment]
Dei todos os privilégios na DB, usando os comandos:
```
GRANT ALL PRIVILEGES ON DATABASE database TO user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO user;
```

E sim, estou executando pelo terminal do VS Code com `python src/A_GUI.py` e clicando para salvar na DB através do GUI TKinter.

Resposta do comando \du:
![image](https://github.com/allanbmartins/Projeto_ETL_RFB_IBGE_ANP/assets/64219777/32018836-3b0f-4c71-995e-82cc888cbdd0)

**Comment by allanbmartins** [comment]
Referente este mensagem "Apesar que alguns posts mencionam que esse erro pode ser de falta de privilégio não no banco, más sim no seu sistema operacional, notei que vc colocou no drive C:, se possível faça o teste no D:, e verifique se seu login/usuário tem acesso completo de administrador no pc, por desencargo de consciência.", vc fez o teste de troca de local do projeto para D:?

**Comment by joaotonaco** [comment]
> Referente este mensagem "Apesar que alguns posts mencionam que esse erro pode ser de falta de privilégio não no banco, más sim no seu sistema operacional, notei que vc colocou no drive C:, se possível faça o teste no D:, e verifique se seu login/usuário tem acesso completo de administrador no pc, por desencargo de consciência.", vc fez o teste de troca de local do projeto para D:?

Não possuo um disco D:, e sim, sou administrador total do sistema.

**Comment by allanbmartins** [comment]
Caso tenha disponibilidade baixe a extensão do TeamViewer desse link: https://download.teamviewer.com/download/TeamViewerQS.exe?utm_source=google&utm_medium=cpc&utm_campaign=br%7Cb%7Cpr%7C22%7Coct%7Ctv-core-generic-sn%7Cnew%7Ct0%7C0&utm_content=Remote-Access&utm_term=acesso+remoto+teamviewer

Para que eu possa fazer um acesso remoto para que eu possa tentar te ajudar.
Baixando executando me envie o seu código de sessão e senha o meu email: allanbmartins@yahoo.com

**Comment by allanbmartins** [comment]
Só vou estar disponível para te ajudar até as 15:30, após isso só amanhã a partir das 08:00, ok.

**Comment by joaotonaco** [comment]
Enviei as credenciais

**Comment by allanbmartins** [comment]
Conforme acesso remoto realizado, foi sanado os problemas.
