### ISSUE TITLE
Erro conexão com Postgres

### ISSUE THREAD

**Issue by lumardi** [allanbmartins/Projeto_ETL_RFB_IBGE_ANP#8]
Caro,
Seguindo aqui as abas da sua interface gráfica, consigo rodar normalmente os códigos das abas `variáveis ambiente`, `diretórios`, e os scripts de download.
Estou com problema na hora de usar a aba `Banco_Dados` tanto ao exibir quanto criar um novo banco de dados no postgres.

Seguindo o log de erros, as seguintes mensagens retornam:

# Exibir bancos de dados existentes:

psycopg2.OperationalError
ERROR:[01/10/2024 04:22:06 PM]: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(gerenciar_bancos) finalizada com erro abaixo: 
 (cannot unpack non-iterable NoneType object)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "c:\Users\lucas\Downloads\Projeto_ETL_RFB_IBGE_ANP-master\Projeto_ETL_RFB_IBGE_ANP-master\src\B_Def_Global.py", line 348, in gerenciar_bancos
    cur, pg_conn = conecta_bd_generico("postgres")
    ^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

# Criar banco de dados:
psycopg2.OperationalError
ERROR:[01/10/2024 04:22:24 PM]: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(gerenciar_bancos) finalizada com erro abaixo: 
 (cannot unpack non-iterable NoneType object)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "c:\Users\lucas\Downloads\Projeto_ETL_RFB_IBGE_ANP-master\Projeto_ETL_RFB_IBGE_ANP-master\src\B_Def_Global.py", line 393, in gerenciar_bancos
    cur, pg_conn = conecta_bd_generico("postgres")
    ^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

Saberia indicar o que estou fazendo de errado?
Como ambos são problemas de conexão, imagino que errei em algum momento de instalar e/ou dar permissão a algo no postgres.

Obrigado!

**Comment by allanbmartins** [comment]
Boa noite prezado

Primeiramente eu já identifiquei um problema que você não colocou o projeto na raiz do "c" ou na raiz do "d", como vc fez "c:\Users\lucas\Downloads\Projeto_ETL_RFB_IBGE_ANP-master\Projeto_ETL_RFB_IBGE_ANP-master\src\B_Def_Global.py", você colocou dentro do profile do seu usuário do Windows isso dá muito problema de incompatibilidade, fora isso você executou todos os passos de criação de usuário super no postgresql?
Por favor corrija colocando o projeto na raiz do seu disco rígido ou drive d, e siga os passos referente a liberação acesso para usuário no postgresql descritas no tutorial do projeto.

Att.

AllanBM

**Comment by allanbmartins** [comment]
Caso não consiga realizando os passos que eu falei mande o seu contato do WhatsApp para o e-mail allanbmartins@yahoo.com, para que eu possa te ajudar via acesso remoto, no horário comercial.

Ok👍

**Comment by allanbmartins** [comment]
Caso não consiga realizar os passos que eu mandei, me mande seu contato do WhatsApp para o e-mail [allanbmartins@yahoo.com](mailto:allanbmartins@yahoo.com), para que eu possa te ajudar via acesso remoto, no horário comercial.

Ok👍

**Comment by lumardi** [comment]
Opa!
Obrigado mesmo pela ajuda, tive certas dificuldades mas consegui.

Aproveito o espaço aqui para não abrir uma nova issue:
Não estou conseguindo baixar os dados auxiliares do município na aba `Script IBGE` (`tb_aux_municipios_ibge_rfb.csv`). 
Tentei tanto pelo `Baixar Todas Tabelas (...)` quanto pelo `Baixar Tabela Auxiliar (...)`, retornando um erro de que não consigo baixar os arquivos.

Obrigado pela ajuda e pelo seu trabalho!

**Comment by allanbmartins** [comment]
Bom dia, prezado

Tem um arquivo "log.log", que foi criado para capturar todos os erros, envio o que está descrito sobre o problema acima citado "Script IBGE( tb_aux_municipios_ibge_rfb.csv)" para análise, hoje as 08:10 fiz o teste tendo sido baixado normalmente, tente novamente e caso não consiga, faça conforme dito anteriormente.

Quanto ao agradecimento, foi para isso mesmo que compartilhei o código, para ajudar outras pessoas que necessitassem das mesmas informações.

**Comment by allanbmartins** [comment]
Como não houve resposta do segundo questionamento entende-se que está resolvido então vou fechar essa conversa
